server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qa_test
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

  flyway:
    locations: classpath:db/migration, classpath:qa/db/migration
#  application:
#    name: