server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_test
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  flyway:
    locations: classpath:db/migration, classpath:dev/db/migration
#  application:
#    name: