spring:
  profiles:
    active: dev
#  profiles:
#    active: qa
  application:
    name: App Courses

# java -jar course.jar --spring.profiles.active=dev
#thats just for continuous integration

#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/test
#    username: postgres
#    password: 1234
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        ddl-auto: update